apiVersion: v1
kind: ConfigMap
metadata:
  namespace: bookthief
  name: bookthief-v3-quicsec-configmap
  labels:
    release: bookthief-v3-quicsec-cm
data:
  quicsec-config.json: |
    {
        "quicsec": {
          "authz_rules": [
            "spiffe://bookstore-v3.bookstore.svc.cluster.local/ns/bookstore/sa/bookstore"
          ]
        }
    }
