kind: Service
apiVersion: v1
metadata:
  name: bookthief-prom
  namespace: bookthief
  labels:
    app: bookthief-prom
    qs-monitoring: enabled
spec:
  selector:
    app: bookthief-v3
  ports:
  - name: metrics
    port: 9090

