kind: Service
apiVersion: v1
metadata:
  name: bookstore-prom
  namespace: bookstore
  labels:
    app: bookstore-prom
    qm-monitoring: enabled
spec:
  selector:
    app: bookstore
  ports:
  - name: qm-fproxy-metrics
    port: 9901

