kind: Service
apiVersion: v1
metadata:
  name: bookbuyer-prom
  namespace: bookbuyer
  labels:
    app: bookbuyer-prom
    qm-monitoring: enabled
spec:
  selector:
    app: bookbuyer
  ports:
  - name: qm-fproxy-metrics
    port: 9901

