apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-qm-alerts
  namespace: qm-monitoring
  labels:
    alertmanagerConfig: qm-alerts
spec:
  #global:
  #  resolveTimeout: 5m
  route:
    groupBy: ['alertname', 'downstreamId', 'myId']
    groupWait: 45s
    groupInterval: 600m  # Interval for added alerts to a group, set it to 10 hours 
    repeatInterval: 1440m  # Alert will not be sent more than once every 24 hours for a given downstreamId.
    receiver: 'slack-webhook'
  receivers:
  - name: 'slack-webhook'
    slackConfigs:
    - channel: '#Your-Slack-Alerts-Channel'
      apiURL:
        name: alertmanager-secrets
        key: slack-api-url
      #username: AlertManager
---
apiVersion: v1
data:
  alertmanager.yaml: ProvideYourBase64EncodedAlertmanagerYamlHere
kind: Secret
metadata:
  name: alertmanager-alertmgr
  namespace: qm-monitoring
type: Opaque
---
