---
# loki-metrics monitoring
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki-qm-servicemonitor
  namespace: qm-monitoring
  labels:
    qm-monitoring: enabled
    serviceMonitorSelector: prometheus
spec:
  endpoints:
  - interval: 30s
    targetPort: 3100
    #port: loki
    path: /metrics
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_version]
      targetLabel: version
  namespaceSelector:
    matchNames:
    - qm-monitoring
  selector:
    matchLabels:
      qm-monitoring: enabled
      app.kubernetes.io/name: loki
---
