---
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: servicemonitor
    app.kubernetes.io/instance: controller-manager-metrics-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: control-plane
    app.kubernetes.io/part-of: control-plane
    app.kubernetes.io/managed-by: kustomize
    qm-monitoring: enabled
  name: controller-manager-metrics-monitor
  namespace: qm-monitoring
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - quicmesh-system
  selector:
    matchLabels:
      control-plane: controller-manager
---
