apiVersion: v1
data:
  loki.yaml: |-
    auth_enabled: false
    chunk_store_config:
      max_look_back_period: 0
    ingester:
      chunk_block_size: 262144
      chunk_idle_period: 15m
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      wal:
        dir: "/tmp/wal"
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_global_streams_per_user: 10000
    schema_config:
      configs:
      - from: "2023-03-18"
        index:
          # 24h retention period for logs
          period: 24h
          prefix: index_
        object_store: filesystem
        schema: v12
        store: boltdb
    server:
      http_listen_port: 3100
    storage_config:
      boltdb:
        directory: /data/loki/index
      filesystem:
        directory: /data/loki/chunks
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: loki
    app.kubernetes.io/name: loki
    qm-monitoring: enabled
  name: loki-config
  namespace: qm-monitoring

