apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qs-bookstore-servicemonitor
  namespace: qm-monitoring
  labels:
    qm-monitoring: enabled
spec:
  namespaceSelector:
    any: true
    #matchNames:
    #- bookstore
  selector:
    matchLabels:
      qs-monitoring: enabled
  endpoints:
  - port: metrics
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_version]
      targetLabel: version
---
