apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
  name: grafana-config
  namespace: qm-monitoring
data:
  GF_INSTALL_PLUGINS: "https://github.com/knightss27/grafana-network-weathermap/releases/download/v0.4.3/knightss27-weathermap-panel-0.4.3.zip;custom-plugin,https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/releases/download/v4.1.1/novatec-sdg-panel.zip;custom-plugin-2"
  GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "true"

