{
 "title": "Service Metrics - QM Service (by Downstreams)",
 "description": "QM Service - Downstreams Dashboard",
 "tags": [ "qm-monitoring" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "downstreamService", "label": "Downstream Service", "query": { "query": "label_values(downstreamId)" } },
   { "name": "qmService", "label": "qmService", "query": { "query": "label_values(myId)" } },
   { "name": "qmService_labelupstream", "label": "qmService Name", "query": { "query": "label_values(upstream)" } },
   {
    "name": "version",
    "label": "qmServiceVersion",
    "query": {
     "query": "label_values({myId=\"$qmService\"}, version)"
    }
   },
   {
    "name": "K6RequestName",
    "label": "K6 Request Name",
    "query": {
     "query": "label_values(k6_http_req_duration_count, name)"
    }
   },
   {
    "name": "GoHttpMetricName",
    "label": "Go HTTP Metric Name",
    "query": "req_duration,req_blocked,req_connecting,req_receiving,req_sending,req_tls_handshaking,req_waiting"
   },
   { "name": "dashboardType", "label": "Dashboard Type", "query": "performance,security,custom" }
  ]
 },
 "panels": [
  {
   "title": "Global Security Metrics - ${qmService}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ASDEX (App Security Index )",
   "type": "stat",
   "description": "Application Security Index\n0.0: Insecure (identity lacking, no defense)\n0.5: Suspect (Identity present, no defense)\n1.0: Safer (Identity present, defenses active)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  0.9 * sum((rate(appedge_inbound_cx_total{policy=\"strict\", verdict=\"authorized\"}[2m]) * 60) OR on() vector(0))\n  + 0.8 * sum((rate(appedge_inbound_cx_total{policy=\"strict\", verdict=\"unauthorized\"}[2m]) * 60) OR on() vector(0))\n  + 0.1 * sum((rate(appedge_inbound_cx_total{policy=\"default\", verdict=\"unauthorized\"}[2m]) * 60) OR on() vector(0))\n) \n/\nsum(rate(appedge_inbound_cx_total{policy=~\"default|strict\", verdict=~\"authorized|unauthorized\"}[2m]) * 60)\n",
     "legendFormat": "ASDEX"
    }
   ]
  },
  {
   "title": "QM mTLS Auth Failures",
   "type": "stat",
   "description": "mTLS Failures - Connection attempts by clients with unauthorized SPIFFE IDs",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(appedge_inbound_cx_total{verdict=\"unauthorized\"}[$__rate_interval])) by (downstreamId) OR on() vector(0) ",
     "legendFormat": "{{downstreamId}} Auth Failure Rate "
    }
   ]
  },
  {
   "title": "QM mTLS Auth Success",
   "type": "stat",
   "description": "mTLS Successes - Connection attempts by clients with authorized SPIFFE IDs",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(appedge_inbound_cx_total{verdict=\"authorized\"}[$__rate_interval])) by (downstreamId) OR on() vector(0) ",
     "legendFormat": "{{downstreamId}}"
    }
   ]
  },
  {
   "title": "${qmService} Service Health - by Downstreams (${downstreamService})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "K6RequestName",
   "targets": [
    {}
   ]
  },
  {
   "title": "APDEX (App Perf Index)",
   "type": "stat",
   "description": "Application Performance Index\n0.0: Bad\n0.5: Average\n1.0: Good ",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentUnit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_check{outcome=\"fail\"}[$__rate_interval])) / sum(rate(k6_check[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (responseCode) (rate(appedge_inbound_rq_total{myId=\"$qmService\"}[$__rate_interval]))",
     "legendFormat": "HTTP {{responseCode}}"
    }
   ]
  },
  {
   "title": "Connection Failures",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (responseCode) (rate(appedge_outbound_cx_connect_fail{upstream=\"dynamic_forward_proxy_cluster\"}[$__rate_interval])) OR on() vector(0)",
     "legendFormat": "Connection Errors {{responseCode}}"
    }
   ]
  },
  {
   "title": "Latency (${GoHttpMetricName}) - ms",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(appedge_outbound_rq_latency_bucket{upstream=\"${qmService_labelupstream:raw}\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (responsecode) (rate(appedge_outbound_rq_total{upstream=\"${qmService_labelupstream:raw}\", responseCode!=\"200\"}[$__rate_interval]))",
     "legendFormat": "HTTP {{responseCode}}"
    }
   ]
  },
  {
   "title": "HTTP/3 Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (responseCode, upstream) (rate(appedge_outbound_cx_http3_total[$__rate_interval]))",
     "legendFormat": "HTTP3 {{namespace}}"
    }
   ]
  },
  {
   "title": "P50 latency (${GoHttpMetricName})",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(appedge_outbound_rq_latency_bucket{upstream=\"${qmService_labelupstream:raw}\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "P90 latency (${GoHttpMetricName})",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(appedge_outbound_rq_latency_bucket{upstream=\"${qmService_labelupstream:raw}\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "Downstreams by IdentitySets: ${IdSets}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "version",
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (responseCode, downstreamId, path) (rate(appedge_outbound_rq_total{myId=\"${downstreamService}\"}[$__rate_interval]))",
       "legendFormat": "{{downstreamId}} HTTP {{path}} {{responseCode}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(k6_script_errors[$__rate_interval]))",
       "legendFormat": "Script errors"
      }
     ]
    },
    {
     "title": "Latency (${GoHttpMetricName})",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 9, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(appedge_outbound_rq_latency_bucket{upstream=\"${qmService_labelupstream:raw}\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "P50 latency (${GoHttpMetricName})",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 17, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(appedge_outbound_rq_latency_bucket{upstream=\"${qmService_labelupstream:raw}\"}[$__rate_interval])) by (le))"
      }
     ]
    },
    {
     "title": "APDEX (ToDo)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentUnit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(k6_check{outcome=\"fail\"}[$__rate_interval])) / sum(rate(k6_check[$__rate_interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Downstreams by version: ${version}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "version",
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (responseCode, downstreamId, path) (rate(appedge_outbound_rq{myId=\"${qmService}\"}[$__rate_interval]))",
       "legendFormat": "HTTP {{responseCode}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(k6_script_errors[$__rate_interval]))",
       "legendFormat": "Script errors"
      }
     ]
    },
    {
     "title": "Latency (${GoHttpMetricName})",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 9, "y": 70 },
     "targets": [
      {
       "expr": "sum(rate(appedge_outbound_rq_latency_bucket{upstream=\"${qmService_labelupstream:raw}\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "P50 latency (${GoHttpMetricName})",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 17, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(appedge_outbound_rq_latency_bucket{upstream=\"${qmService_labelupstream:raw}\"}[$__rate_interval])) by (le))"
      }
     ]
    },
    {
     "title": "APDEX (ToDo)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percentUnit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(k6_check{outcome=\"fail\"}[$__rate_interval])) / sum(rate(k6_check[$__rate_interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Canary distribution to ${qmService} versions from Downstreams (${downstreamService})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "downstreamService",
   "collapsed": true,
   "panels": [
    {
     "title": "${downstreamService:raw} -> ${qmService} Requests by Service Version",
     "type": "barchart",
     "description": "HTTP Requests by Service Version",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (version) (rate(appedge_inbound_rq_total{myId=\"${qmService}\",downstreamId=\"${downstreamService:raw}\"}[$__rate_interval])  )",
       "legendFormat": "{{version}}"
      },
      {
       "expr": "sum by (version) (rate(http_request_network_latency_count{container=\"bookbuyer-v3\"}[$__rate_interval]) )",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Bookbuyer- Bookstore: Rate of Successful Requests and Errors (by version)",
     "type": "timeseries",
     "description": "Bookbuyer- Bookstore: Rate of Successful Requests and Errors (by version)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum by (version) (rate(appedge_outbound_rq_total{job=\"bookbuyer-prom\", upstream=\"dynamic_forward_proxy_cluster\"}[$__rate_interval]) )",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (version) (rate(http_request_network_latency_count{job=\"bookbuyer-native-prom\"}[$__rate_interval]) )",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "sum by (version) (rate(http_request_status_counter{job=\"bookbuyer-native-prom\", responseCode!=\"200\"}[$__rate_interval]) )",
       "legendFormat": "Error Rate: {{version}}"
      },
      {
       "expr": "sum by (version) (rate(appedge_outbound_rq_xx{job=\"bookbuyer-prom\", upstream=\"${qmService}\", responseCodeClass=\"5\"}[$__rate_interval]))",
       "legendFormat": "Error Rate: {{version}}"
      }
     ]
    }
   ]
  },
  { "title": "Security Stats (by Identities)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "version" },
  {
   "title": "QM mTLS Auth Errors",
   "type": "timeseries",
   "description": "mTLS Failures - Connection attempts by clients with unauthorized SPIFFE IDs",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(appedge_inbound_cx_total{verdict=\"unauthorized\"}[$__rate_interval])) by (downstreamId) OR on() vector(0)",
     "legendFormat": "{{downstreamId}}"
    }
   ]
  },
  {
   "title": "QM mTLS Auth Success",
   "type": "timeseries",
   "description": "mTLS Failures - Connection attempts by clients with authorized SPIFFE IDs",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(appedge_inbound_cx_total{verdict=\"authorized\"}[$__rate_interval])) by (downstreamId) OR on() vector(0)",
     "legendFormat": "{{downstreamId}}"
    }
   ]
  },
  {
   "title": "Logs: ${qmService} by Downstreams (${downstreamService})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${downstreamService} (Downstream) - ${qmService} (QM-Service) AppEdge Logs",
     "type": "logs",
     "description": "${downstreamService} (Downstream) - ${qmService} (QM-Service) AppEdge Logs",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "{myId=\"$qmService\"} |= `UNAUTHORIZED`"
      },
      {
       "expr": "{container_name=\"reverse-proxy\"} | json downstreamId=\"downstreamService\""
      }
     ]
    }
   ]
  }
 ]
}