{
 "title": "QuicMesh Map",
 "description": "QuicMesh Service Map",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "QuicMesh Service Map",
   "type": "knightss27-weathermap-panel",
   "description": "Map of QuicMesh Services",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_cluster_name=\"dynamic_forward_proxy_cluster\", envoy_response_code_class=\"2\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_request_status_counter{status=\"200\"}[$__rate_interval])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bookbuyer -> Bookstore Requests by Service Version",
   "type": "barchart",
   "description": "HTTP Requests by Service Version",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (version) (rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"dynamic_forward_proxy_cluster\"}[$__rate_interval])  )",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "sum by (version) (rate(http_request_network_latency_count{container=\"bookbuyer-v3\"}[$__rate_interval]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bookthief -> Bookstore Requests by Service Version",
   "type": "barchart",
   "description": "HTTP Requests by Service Version",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (version) (rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"dynamic_forward_proxy_cluster\"}[$__rate_interval])  )",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "sum by (version) (rate(http_request_network_latency_count{container=\"bookthief-v3\"}[$__rate_interval]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bookbuyer - Bookstore access by Version and Error Rate",
   "type": "timeseries",
   "description": "Bookthief - Bookstore access by Version and Latency, Error-rate",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (version) (rate(envoy_cluster_upstream_rq_xx{envoy_cluster_name=\"dynamic_forward_proxy_cluster\", envoy_response_code_class=\"5\"}[$__rate_interval]))",
     "legendFormat": "{{version}} Error Rate "
    },
    {
     "expr": "sum by (version) (rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"dynamic_forward_proxy_cluster\"}[$__rate_interval]) )",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (version) (rate(http_request_network_latency_count{container=\"bookbuyer-v3\"}[$__rate_interval]) )",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum by (version) (rate(http_request_status_counter{container=\"bookthief-v3\", status!=\"200\"}[$__rate_interval]) )",
     "legendFormat": "{{version}} Error Rate"
    },
    {
     "expr": "rate(quic_connection_errors_total{namespace=\"bookbuyer\"}[$__rate_interval]) ",
     "legendFormat": "{{container}}  Error rate"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(http_request_network_latency_bucket{namespace=\"bookbuyer\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bookthief - Bookstore access by Version and Error Rate",
   "type": "timeseries",
   "description": "Bookthief - Bookstore access by Version and Latency, Error-rate",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 18 },
   "targets": [
    {
     "expr": "sum by (version) (rate(envoy_cluster_upstream_rq_xx{envoy_cluster_name=\"dynamic_forward_proxy_cluster\", envoy_response_code_class=\"5\"}[$__rate_interval]))",
     "legendFormat": "{{version}} Error Rate "
    },
    {
     "expr": "sum by (version) (rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"dynamic_forward_proxy_cluster\"}[$__rate_interval]) )",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (version) (rate(http_request_network_latency_count{container=\"bookbuyer-v3\"}[$__rate_interval]) )",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum by (version) (rate(http_request_status_counter{container=\"bookthief-v3\", status!=\"200\"}[$__rate_interval]) )",
     "legendFormat": "{{version}} Error Rate"
    },
    {
     "expr": "rate(quic_connection_errors_total[$__rate_interval]) ",
     "legendFormat": "{{container}} Error rate"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(http_request_network_latency_bucket{namespace=\"bookbuyer\"}[$__rate_interval])))",
     "legendFormat": "{{container}} P75"
    }
   ]
  },
  {
   "title": "QuicSec Blog",
   "type": "news",
   "description": "QuicSec Blog Stream",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 24 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pod8 Blog",
   "type": "news",
   "description": "Pod8 Blog Stream",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 24 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  }
 ]
}