# Source: prometheus-operator/templates/grafana/configmaps-datasources.yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources-qm-monitoring
  namespace: qm-monitoring
  labels:
    grafana_datasource: "1"
    app: prometheus-operator-grafana
type: Opaque
stringData:
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                #"access": "proxy",
                #"isDefault": true,
                "editable": false,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-operated.qm-monitoring:9090/",
                "version": 1
            },
            {
                #"access": "proxy",
                #"isDefault": true,
                "editable": false,
                "name": "loki",
                "orgId": 1,
                "type": "loki",
                "url": "http://loki.qm-monitoring:3100/",
                "version": 1
            }
        ]
    }
