apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: qm-monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
  name: grafana
  namespace: qm-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: grafana
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/component: grafana
        app.kubernetes.io/name: grafana
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: grafana/grafana:9.2.5
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          name: http
        envFrom:
          - configMapRef:
              name: grafana-config
        env:
        #  - name: GF_INSTALL_PLUGINS
        #    value: "https://github.com/knightss27/grafana-network-weathermap/releases/download/v0.3.5/knightss27-weathermap-panel-0.3.5.zip;custom-plugin"
          - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
            value: "/grafana-dashboard-definitions/0/grafana-dashboard-home/home.json"
          - name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
            value: "knightss27-weathermap-panel"
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
          readOnly: false
        - mountPath: /tmp
          name: grafana-tmp
          readOnly: false
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-datasources
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/grafana-dashboard-home
          name: grafana-dashboard-home
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/grafana-dashboard-quicmeshmap
          name: grafana-dashboard-quicmeshmap
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/grafana-dashboard-downstreams
          name: grafana-dashboard-downstreams
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/grafana-dashboard-quicstats
          name: grafana-dashboard-quicstats
          readOnly: false
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-dashboards-qm-monitoring
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/grafana-dashboard-k6
          name: grafana-dashboard-k6
          readOnly: false
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: grafana
      volumes:
      - emptyDir: {}
        name: grafana-storage
      - emptyDir: {}
        name: grafana-tmp
      - name: grafana-datasources
        secret:
          secretName: grafana-datasources-qm-monitoring
      - configMap:
          name: grafana-dashboard-home
        name: grafana-dashboard-home
      - configMap:
          name: grafana-dashboard-quicmeshmap
        name: grafana-dashboard-quicmeshmap
      - configMap:
          name: grafana-dashboard-downstreams
        name: grafana-dashboard-downstreams
      - configMap:
          name: grafana-dashboard-k6
        name: grafana-dashboard-k6
      - configMap:
          name: grafana-dashboard-quicstats
        name: grafana-dashboard-quicstats
      - configMap:
          name: grafana-dashboards-qm-monitoring
        name: grafana-dashboards-qm-monitoring
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
  name: grafana
  namespace: qm-monitoring
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana

