---
apiVersion: v1
kind: Namespace
metadata:
  name: qm-monitoring
  labels:
    bookstore-demo: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: bookbuyer
  labels:
    bookstore-demo: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: bookthief
  labels:
    bookstore-demo: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: bookwarehouse
  labels:
    bookstore-demo: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: bookstore
  labels:
    bookstore-demo: "true"

---


