apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookthief
  namespace: bookthief
  labels:
    app: bookthief
spec:
  rules:
  - host: "bookthief.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bookthief
            port:
              number: 14001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookbuyer
  namespace: bookbuyer
  labels:
    app: bookbuyer
spec:
  rules:
  - host: "bookbuyer.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bookbuyer
            port:
              number: 14001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-service
  namespace: monitoring
  labels:
    app: prometheus
spec:
  rules:
  - host: "prometheus.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-service
            port:
              number: 9090

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-service
  namespace: monitoring
  labels:
    app: grafana
spec:
  rules:
  - host: "grafan.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana-service
            port:
              number: 3000

---
