---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bookstore
  namespace: bookstore
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bookstore
  namespace: bookstore
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bookstore
subjects:
- kind: ServiceAccount
  name: bookstore
  namespace: bookstore
---
