---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-v3
  namespace: bookstore
  labels:
    app: bookstore-v3
spec:
  ports:
  - port: 14001
    name: bookstore-v3
    protocol: UDP
  selector:
    app: bookstore-v3
---
