---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookbuyer-v3
  namespace: bookbuyer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookbuyer-v3
      version: v3
  template:
    metadata:
      labels:
        app: bookbuyer-v3
        version: v3
        qs-monitoring: enabled
    spec:
      serviceAccountName: bookbuyer
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
        - name: bookbuyer-v3
          image: ghcr.io/quicsec/bookbuyer:qsv0.15
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 14001
            name: bookbuyer-v3
          - containerPort: 9090
            name: metrics
            protocol: TCP
          command: ["/bookbuyer"]
          env:
            - name: BOOKSTORE_NAMESPACE
              value: bookstore
            - name: BOOKSTORE_SVC
              value: bookstore-v3
            - name: BOOKSTORE_SVC_PORT
              value: "14001"
            - name: WAREHOUSE_SVC
              value: bookwarehouse
            - name: CI_MAX_ITERATIONS_THRESHOLD
              value: "60"
            - name: ENABLE_EGRESS
              value: "true"
            - name: CI_CLIENT_CONCURRENT_CONNECTIONS
              value: "1"
            - name: CI_SLEEP_BETWEEN_REQUESTS_SECONDS
              value: "5"
            - name: QUICSEC_CERT_FILE
              value: "/var/run/secrets/spiffe.io/tls.crt"
            - name: QUICSEC_KEY_FILE
              value: "/var/run/secrets/spiffe.io/tls.key"
            - name: QUICSEC_CA_FILE
              value: "/var/run/secrets/spiffe.io/ca.crt"
            - name: QUICSEC_AUTHZ_RULES_PATH
              value: "/etc/quicsec/quicsec-config.json"
            - name: QUICSEC_INSEC_SKIP_VERIFY
              value: "1"
            - name: QUICSEC_PROMETHEUS_BIND
              value: "0.0.0.0:9090"
            - name: QUICSEC_QLOG_DIR_PATH
              value: ""
          volumeMounts:
          - name: spiffe
            mountPath: "/var/run/secrets/spiffe.io"
          - name: quicsec-config
            mountPath: "/etc/quicsec"
      volumes:
      - name: quicsec-config
        configMap:
          name: bookbuyer-v3-quicsec-configmap
      - name: spiffe
        csi:
          driver: spiffe.csi.cert-manager.io
          readOnly: true
---
