---
apiVersion: v1
kind: Service
metadata:
  name: bookbuyer-v3
  namespace: bookbuyer
  labels:
    app: bookbuyer-v3
    qs-monitoring: enabled
spec:
  ports:
  - port: 14001
    name: bookbuyer-v3
  selector:
    app: bookbuyer-v3
---
