---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bookthief
  namespace: bookthief
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bookthief
  namespace: bookthief
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bookthief
subjects:
- kind: ServiceAccount
  name: bookthief
  namespace: bookthief
---
