apiVersion: v1
kind: ConfigMap
metadata:
  namespace: bookthief
  name: bookthief-v3-quicsec-configmap
  labels:
    release: bookthief-v3-quicsec-cm
data:
  quicsec-config.json: |
      {
          "version": "v1alpha2",
          "qm_service_conf": [
              {
                      "server_instance_key": "127.0.0.1",
                      "policy":{
                              "*": {
                                      "authz": "allow"
                              },
                              "spiffe://anotherdomain.foo.bar/foo/bar": {
                                      "authz": "allow"
                              }
                      },
                      "client_cert": true
          }]
      }