---
apiVersion: v1
kind: Service
metadata:
  name: bookthief-v3
  namespace: bookthief
  labels:
    app: bookthief-v3
    qs-monitoring: enabled
spec:
  ports:
  - port: 14001
    name: bookthief-v3
  selector:
    app: bookthief-v3

---
